void reset_to_98(int *n);
void swap_int(int *a, int *b);
int _strlen(char *s);
void _puts(char *str);
void print_rev(char);
void rev_string(char);
void puts2(char);
void puts_half(char);
void print_array(int, int);
char *_strcpy(char, char);
